### ISSUE TITLE
Extension des fichiers markdown

### ISSUE THREAD

**Issue by samuelortion** [YvesBas/Tadarida-C#5]
Tu devrais changer l'extension de ton fichier README.txt, au profit de .md pour que Github fasse le rendu correctement,
Cordialement,
Samuel ORTION

**Comment by rduivenvoorde** [comment]
Hi Samuel, just wondering about which README.txt you are asking? Because 
https://github.com/YvesBas/Tadarida-C/blob/master/README.md
is already markdown, and I do not see a README.txt?

**Comment by rduivenvoorde** [comment]
Ah sorry in the commits I now see, that it apparently changed extension after you created this issue:
https://github.com/YvesBas/Tadarida-C/commits/master

So this could be closed?

**Comment by samuelortion** [comment]
Of course ;-)
