### ISSUE TITLE
Pull Requests or some code/doc changes?

### ISSUE THREAD

**Issue by rduivenvoorde** [YvesBas/Tadarida-C#6]
@YvesBas as a R-beginner I'm trying to use Tadarida-C and had some troubles because (well all kind of R related things... but also) of the fact thta the main scripts seem to be used as standalone scripts?
So there are some hardcode arguments/variables or full paths, which in my case do not seem to play nice together.

I wonder if anyone would be interested is discussion or actually doing some code (together?)  to make sure that beginners actually can run some tests without fiddling with the arguments in the different scripts?

Thinking about:
- given we have 2 steps (creating learner and using learner), it would mabye be nice if all the variables/arguments for those would be descriptive given names, so in code they are more recognizable then arg[14] etc etc?
It would be nice to be able to run both main scripts by just starting them in the right directory and they would pick up the arguments from some inputs.R file or so? And also make it possible to actually use them als arguments though.

Question: is the odt-file still uptodate? Or is the README.md actually better? Maybe it is an idea to actually create a doc directory with some markdown files as documentation? Then others can easily fix/add information (via github/pull requests)?

If anybody is interested in (helping) with such work, please let me know.

**Comment by YvesBas** [comment]
Hi Richard! It may be not suitable for your use, but this "args" syntax aims at using those script with Rscript on a server, so that you can add each arguments in the right order in the command line. Would that help? We are working on a deep learning version of Tadarida so I'm not sure I'll have time to make more user-friendly code on my side, sorry...
